### ISSUE TITLE
Full Name / Full Title fields are not showing value in admin page for speakers / workshops

### ISSUE THREAD

**Issue by product-mindset** [product-mindset/site#71]
See attached screenshots:
<img width="964" alt="screen shot 2018-04-02 at 11 27 19 am" src="https://user-images.githubusercontent.com/37353123/38202340-608215b0-3669-11e8-974c-83a471413cc9.png">
<img width="963" alt="screen shot 2018-04-02 at 11 27 38 am" src="https://user-images.githubusercontent.com/37353123/38202349-63d40d2c-3669-11e8-96c4-9c6b850044e2.png">

This is typically due to a typo / mistake in `config.yml` or something not matching the markdown frontmatter.

Actually ... looks like there's an extra `l`in frontmatter
https://github.com/product-mindset/site/blob/master/content/speakers/Kloepping.md
`fulllName`

**Comment by derektiffany** [comment]
fixed with #72
